#!/usr/bin/env python3
"""
若依系统 OpenAPI 文档解析器
用于从 OpenAPI 文档生成 API 代码
"""

import json
import sys
from pathlib import Path
from typing import Dict, List, Any


class RuoyiAPIParser:
    """若依 API 解析器"""

    def __init__(self, spec_path: str):
        self.spec_path = Path(spec_path)
        with open(self.spec_path, 'r', encoding='utf-8') as f:
            self.spec = json.load(f)

    def get_modules(self) -> Dict[str, List[Dict]]:
        """获取所有模块及其接口"""
        paths = self.spec.get('paths', {})
        modules = {}

        for path, methods in paths.items():
            parts = path.strip('/').split('/')
            if len(parts) >= 2:
                module_name = parts[1]  # 如 user, role, dept
            else:
                continue

            if module_name not in modules:
                modules[module_name] = []

            for method, details in methods.items():
                modules[module_name].append({
                    'path': path,
                    'method': method.upper(),
                    'summary': details.get('summary', ''),
                    'description': details.get('description', ''),
                    'tags': details.get('tags', []),
                    'operationId': details.get('operationId', ''),
                })

        return modules

    def get_module_apis(self, module: str) -> List[Dict]:
        """获取指定模块的所有 API"""
        modules = self.get_modules()
        return modules.get(module, [])

    def parse_schema(self, schema: Dict, refs: Dict = None) -> str:
        """解析 Schema 为 TypeScript 类型"""
        if refs is None:
            refs = {}

        if '$ref' in schema:
            ref = schema['$ref']
            ref_name = ref.split('/')[-1]
            return ref_name

        schema_type = schema.get('type', 'any')

        if schema_type == 'object':
            if 'properties' in schema:
                props = []
                required = schema.get('required', [])
                for prop_name, prop_schema in schema['properties'].items():
                    prop_type = self.parse_schema(prop_schema, refs)
                    is_optional = prop_name not in required
                    optional_mark = '?' if is_optional else ''
                    props.append(f"  {prop_name}{optional_mark}: {prop_type};")
                return '{\n' + '\n'.join(props) + '\n}'
            return 'Record<string, any>'

        elif schema_type == 'array':
            items = schema.get('items', {})
            item_type = self.parse_schema(items, refs)
            return f"{item_type}[]"

        elif schema_type == 'string':
            format_val = schema.get('format', '')
            if format_val == 'date-time':
                return 'string'
            elif format_val == 'date':
                return 'string'
            return 'string'

        elif schema_type == 'integer':
            return 'number'

        elif schema_type == 'number':
            return 'number'

        elif schema_type == 'boolean':
            return 'boolean'

        return 'any'

    def get_request_body_schema(self, api: Dict) -> Dict:
        """获取请求体 Schema"""
        method = api['method'].lower()
        path_obj = self.spec['paths'][api['path']][method]

        if 'requestBody' in path_obj:
            content = path_obj['requestBody'].get('content', {})
            if 'application/json' in content:
                return content['application/json'].get('schema', {})
            elif 'multipart/form-data' in content:
                return content['multipart/form-data'].get('schema', {})

        return {}

    def get_response_schema(self, api: Dict) -> Dict:
        """获取响应 Schema"""
        method = api['method'].lower()
        path_obj = self.spec['paths'][api['path']][method]

        if 'responses' in path_obj and '200' in path_obj['responses']:
            content = path_obj['responses']['200'].get('content', {})
            if 'application/json' in content:
                return content['application/json'].get('schema', {})

        return {}


def generate_typescript_api(module: str, apis: List[Dict], parser: RuoyiAPIParser) -> str:
    """生成 TypeScript API 代码"""

    # 提取接口名称
    interface_name = {
        'user': 'User',
        'role': 'Role',
        'dept': 'Dept',
        'menu': 'Menu',
        'post': 'Post',
        'dict': 'Dict',
        'notice': 'Notice',
        'config': 'Config',
    }.get(module, module.capitalize())

    code = f"""// Auto-generated by ruoyi-api skill
// Module: {module}

import {{ request }} from '@/utils/request';

// ==================== 类型定义 ====================

"""

    # 添加通用类型
    code += f"""export interface {interface_name} {{
  id?: number;
  createTime?: string;
  updateTime?: string;
  [key: string]: any;
}}

export interface {interface_name}QueryParams extends PageQuery {{
  [key: string]: any;
}}

export interface PageQuery {{
  pageNum?: number;
  pageSize?: number;
}}

export interface ListResult<T> {{
  total: number;
  rows: T[];
}}

"""

    # 生成 API 方法
    code += f"// ==================== API 方法 ====================\n\n"
    code += f"export const {module}Api = {{\n"

    for api in apis:
        method = api['method'].lower()
        path = api['path']
        summary = api.get('summary', '')

        # 生成方法名
        operation_id = api.get('operationId', '')
        if operation_id:
            # 从 operationId 推断方法名
            method_name = operation_id.replace(f'{module}_', '').replace(f'{module}.', '')
        else:
            # 从路径和方法推断
            if method == 'get' and 'list' in path:
                method_name = 'list'
            elif method == 'post':
                method_name = 'add'
            elif method == 'put':
                method_name = 'update'
            elif method == 'delete':
                method_name = 'remove'
            else:
                method_name = f"{method}_{path.replace('/', '_')}"

        # 生成请求配置
        if method == 'get':
            request_config = f"""{{
      url: '{path}',
      method: 'get',
      params
    }}"""
        elif method == 'delete':
            request_config = f"""{{
      url: path || '{path}',
      method: 'delete'
    }}"""
        else:
            request_config = f"""{{
      url: '{path}',
      method: '{method}',
      data
    }}"""

        # 生成参数
        if method == 'get':
            params = 'params?: any'
        elif method == 'delete':
            params = 'path?: string'
        else:
            params = 'data: any'

        code += f"""  // {summary or path}
  {method_name}: ({params}) => {{
    return request<any>({request_config});
  }},

"""

    code += "};\n"

    return code


def main():
    """主函数"""
    if len(sys.argv) < 2:
        print("Usage: python parser.py <spec.json> [module]")
        print("Example: python parser.py ruoyi-api.json user")
        sys.exit(1)

    spec_path = sys.argv[1]
    parser = RuoyiAPIParser(spec_path)

    if len(sys.argv) >= 3:
        # 生成指定模块
        module = sys.argv[2]
        apis = parser.get_module_apis(module)
        code = generate_typescript_api(module, apis, parser)
        print(code)
    else:
        # 列出所有模块
        modules = parser.get_modules()
        print("可用模块:")
        for module, apis in sorted(modules.items()):
            print(f"  {module}: {len(apis)} 个接口")


if __name__ == '__main__':
    main()
